def create_booking(showtimes: list, seat_maps: dict, booking_data: dict) -> dict: ...
def cancel_booking(bookings: list, booking_id: str, seat_maps: dict) -> bool: ...
def calculate_booking_total(seats: list[str], pricing: dict, tax_rate: float, discounts: list[dict]) -> dict: ...
def list_customer_bookings(bookings: list, email: str) -> list: ...
def generate_ticket(booking: dict, directory: str) -> str: ...