import json

def load_movies(path: str) -> list: ...
def save_movies(path: str, movies: list) -> None: ...
def add_movie(movies: list, movie_data: dict) -> dict: ...
def schedule_showtime(showtimes: list, showtime_data: dict) -> dict: ...
def list_showtimes(showtimes: list, movie_id: str | None = None, date: str| None = None) -> list: ...
def update_showtime(showtimes: list, showtime_id: str, updates: dict) -> dict: ...