def initialize_seat_map(screen_config: dict) -> dict: ...
def render_seat_map(seat_map: dict) -> str: ...
def is_seat_available(seat_map: dict, seat_code: str) -> bool: ...
def reserve_seat(seat_map: dict, seat_code: str) -> dict: ...
def release_seat(seat_map: dict, seat_code: str) -> dict: ...